# Generated by Django 6.0.7 on 2026-09-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Xbox', 'Xbox'), ('Play 1', 'Play 1'), ('Dreamcast', 'Dreamcast')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
